# Generated by Django 3.2 on 2025-02-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_options'),
        ('reviews', '0006_auto_20250203_1147'),
    ]

    operations = [
    ]
